version: '3.4'

services:
  commercial.api:
    image: ${DOCKER_REGISTRY-}commercialapi
    build:
      context: .
      dockerfile: src/Services/Commercial/Commercial.API/Dockerfile
    depends_on:
      - sqlserver 

  marketing.api:
    image: ${DOCKER_REGISTRY-}marketingapi
    build:
      context: .
      dockerfile: src/Services/Marketing/Marketing.API/Dockerfile
    depends_on:
      - sqlserver 
 
  sales.api:
    image: ${DOCKER_REGISTRY-}salesapi
    build:
      context: .
      dockerfile: src/Services/Sales/Sales.API/Dockerfile
    depends_on:
      - sqlserver 
 
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest 




