version: '3.4'

services:
  
  web.spa:
    build: src/web/spa
    command: sh -c "npm start"
    ports:
    - 4200:4200
    working_dir: /home/node/spa
    volumes: 
    - ./:/home/node/spa
    - node_modules:/home/spa/node_modules

  commercial.api:
    image: ${DOCKER_REGISTRY-}commercialapi
    build:
      context: .
      dockerfile: src/Services/Commercial/Commercial.API/Dockerfile

  marketing.api:
    image: ${DOCKER_REGISTRY-}marketingapi
    build:
      context: .
      dockerfile: src/Services/Marketing/Marketing.API/Dockerfile

  sales.api:
    image: ${DOCKER_REGISTRY-}salesapi
    build:
      context: .
      dockerfile: src/Services/Sales/Sales.API/Dockerfile

  rtapigateway:
    image: ${DOCKER_REGISTRY-}rtapigateway
    build:
      context: .
      dockerfile: src/BuildingBlocks/ApiGateway/RTApiGateway/Dockerfile

  rabbitmq:
    image: rabbitmq:3.13-management

volumes:
  node_modules:



