version: '3.4'

services:
  
  commercial.api:
    image: ${DOCKER_REGISTRY-}commercialapi
    build:
      context: .
      dockerfile: src/Services/Commercial/Commercial.API/Dockerfile

  marketing.api:
    image: ${DOCKER_REGISTRY-}marketingapi
    build:
      context: .
      dockerfile: src/Services/Marketing/Marketing.API/Dockerfile

  sales.api:
    image: ${DOCKER_REGISTRY-}salesapi
    build:
      context: .
      dockerfile: src/Services/Sales/Sales.API/Dockerfile

  rtapigateway:
    image: ${DOCKER_REGISTRY-}rtapigateway
    build:
      context: .
      dockerfile: src/BuildingBlocks/ApiGateway/RTApiGateway/Dockerfile

  rabbitmq:
    image: rabbitmq:3.13-management




